Adding User Count Endpoint
Carma-tech/CarmaTech-API pull request #5
Opened 2023-05-10 07:26 UTC by abdullah5abid

2023-05-11 03:05 UTC, tonytan4ever commented
Can you try fix the failing build ?

2023-05-11 03:06 UTC, tonytan4ever commented on src/modules/user/user.controller.ts
> +      console.error(error);
Remove console error.

2023-05-11 03:10 UTC, tonytan4ever requested changes
1. add unit tests.
2. Fix the failing build

2023-05-11 10:47 UTC, abdullah5abid commented
> 
I'm trying to resolve the build error but where to add the unit tests?

2023-05-18 02:38 UTC, tonytan4ever commented on Dockerfile
> +CMD [ "node", "-r", "./tsconfig-paths-bootstrap.js" ,"dist/main.js" ]
Can you remove the empty line?

2023-05-18 02:38 UTC, tonytan4ever commented on docker-compose.yaml
> +  localstack:
Same here, can you remove the empty line here?

2023-05-18 02:40 UTC, tonytan4ever requested changes
Final request:
Can you squash all your 33 commits into one, and fix a few empty lines?
I can merge afterwards.

2023-06-11 01:29 UTC, tonytan4ever approved these changes

2023-06-11 01:29 UTC, merged